### PR TITLE
refactor(app): refactor fetcher + fix issues with some services

### PR DESCRIPTION
**Pull request by qlaffont**
- Refactor to remove axios
- Add more tests by services
- fix issues from  https://github.com/mastermunj/username-checker/issues/81

### CODE REVIEW

**Comment by qlaffont** [comment]
:wave: @mastermunj

**Comment by mastermunj** [comment]
Hi @qlaffont, thank you for the PR. I am not comfortable setting global fetch with isomorphic fetch. I'd still prefer using Axios or maybe default fetch.

**Comment by qlaffont** [comment]
@mastermunj isomorphic fetch is regular fetch (it just a polyfill if needed for node.js environment, so don't worry) !

**Comment by qlaffont** [comment]
if this PR is merged i will work on others issues ;)

**Comment by mastermunj** [comment]
The tests will need to be faked for them to run fast.

**Comment by qlaffont** [comment]
Yes but the issue with mocked tests is you are not sure if tests are working days or months later. (Because API can change)

This is for this reason that I prefer (in this case) to not user mocked tests

**Comment by qlaffont** [comment]
strange tests not working ... in my laptop is working :thinking: can you rerun it ?

**Comment by mastermunj** [comment]
Merged! You can raise the PR for the other changes. Will release them all together then.

**Comment by qlaffont** [comment]
thanks I keep you in touch !

**Pull request merged**
